# Generated by Django 5.1.6 on 2025-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tln',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('input_language', models.CharField()),
                ('output_language', models.CharField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'translation',
            },
        ),
    ]
