# Generated by Django 5.1.6 on 2025-02-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tln',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
