# Generated by Django 5.1.6 on 2025-02-28 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0003_alter_tln_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tln',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
